### ISSUE TITLE
How to pass locals to loader?

### ISSUE THREAD

**Issue by timofei-iatsenko** [bline/jade-html-loader#13]
How to pass locals via this loader? 

I need to pass object with functions, so key/value is not an option. 

I've configuered loader in this way: 

``` js
 { test: /\.jade$/,  loader: 'raw-loader!jade-html-loader' },
```

So i looking for how to pass object into it. For example: 

``` js
 { test: /\.jade$/,  loader: 'raw-loader!jade-html-loader?locals=jadeLocals' },

//then somewehere in wepack config:
{
 jadeLocals: require('myObjectWithFunctions')
}
```

**Comment by simbo** [comment]
same problem here...

**Comment by timofei-iatsenko** [comment]
I forked this repo and implement this feature. 

Check out in my repo https://github.com/thekip/jade-html-loader

When i test it enough i'll make a pull request and write a docs. But currently you have to get it from my repo.

Quick manual: 

add this line to package.json (replace it if you already have)

``` json
"jade-html-loader": "https://github.com/thekip/jade-html-loader#master",
```

then in webpack config: 

``` js
module.exports = {
    module: {
        loaders: {
        // here is as usual
         { test: /\.jade$/,  loader: 'raw-loader!jade-html-loader' },
        }
    },
    jadeLoader: {
    //here you can set any of compiler options, and locals as well
     locals: {
      bem: require('bem-jade')({
        prefix: '',
        element: '__',
        modifier: '--',
        default_tag: 'div',
      })
    },

    basedir: __dirname + '/src'
    }
}
```

**Comment by geyang** [comment]
@thekip Thanks! This should be merged:)

**Comment by timofei-iatsenko** [comment]
I've created a pull request with this feature and detailed readme of that. So if @bline is still maintain this repo, he will merge it. 

But it looks like this repo is currently unmaintained.
