### ISSUE TITLE
How to pass locals?

### ISSUE THREAD

**Issue by azamat-sharapov** [bline/jade-html-loader#2]
I'm trying to pass local variables to use in Jade file, but can't get it working. Here is my loader from my config:

```
{
	test: /\.jade$/,
	loader: 'html!jade-html?locals={one:1}'
}
```

Then trying to access variable in jade file: `#{one}`

**Comment by azamat-sharapov** [comment]
Figured it out, following works:

```
loader: 'html!jade-html?{one:1}'
```

**Comment by indigofeather** [comment]
Useful ! :+1:
